export const PATHS = Object.freeze({
  contract: 'coordination/kidults/runtime/kir-runtime-contract-v1.json',
  registry: 'coordination/kidults/runtime/kir-module-registry-v1.json',
  readiness: 'coordination/kidults/market/current-sold-value-chain-readiness-v1.json',
});

export const REPOSITORY = 'johnkim9524-collab/kaios_enterprise_repo';
export const SHA40 = /^[0-9a-f]{40}$/;
export const DIGEST = /^sha256:[0-9a-f]{64}$/;

export const EXPECTED_DAG = Object.freeze({
  SOURCE_RIGHTS: [],
  RECEIPT_AUTHORITY: [],
  CURRENT_SOLD_ADMISSION: ['SOURCE_RIGHTS', 'RECEIPT_AUTHORITY'],
  CURRENT_SOLD_EVIDENCE: ['CURRENT_SOLD_ADMISSION'],
  APPEND_ONLY_LEDGER: ['CURRENT_SOLD_ADMISSION'],
  CANDIDATE_EVIDENCE_PAIR: ['CURRENT_SOLD_EVIDENCE', 'APPEND_ONLY_LEDGER'],
  TRACK_B_ASSESSMENT: ['CANDIDATE_EVIDENCE_PAIR'],
  PROJECTION_RELEASE: ['TRACK_B_ASSESSMENT'],
});

export const FORWARD_STATE = Object.freeze({
  SOURCE_RIGHTS: 'READY',
  RECEIPT_AUTHORITY: 'READY',
  CURRENT_SOLD_ADMISSION: 'EMPIRICAL_VALIDATED',
  CURRENT_SOLD_EVIDENCE: 'EMPIRICAL_VALIDATED',
  APPEND_ONLY_LEDGER: 'EMPIRICAL_VALIDATED',
  CANDIDATE_EVIDENCE_PAIR: 'PAIR_READY',
  TRACK_B_ASSESSMENT: 'COMPLETE_INDEPENDENT_ASSESSMENT',
  PROJECTION_RELEASE: 'APPROVED_PROJECTION_READY',
});

export const EVIDENCE_KEY = Object.freeze({
  SOURCE_RIGHTS: 'SOURCE_RIGHTS_READY',
  RECEIPT_AUTHORITY: 'RECEIPT_AUTHORITY_READY',
  CURRENT_SOLD_ADMISSION: 'CURRENT_SOLD_ADMISSION_EMPIRICAL_VALIDATED',
  CURRENT_SOLD_EVIDENCE: 'CURRENT_SOLD_EVIDENCE_EMPIRICAL_VALIDATED',
  APPEND_ONLY_LEDGER: 'APPEND_ONLY_LEDGER_EMPIRICAL_VALIDATED',
  CANDIDATE_EVIDENCE_PAIR: 'CANDIDATE_EVIDENCE_PAIR_READY',
  TRACK_B_ASSESSMENT: 'TRACK_B_ASSESSMENT_COMPLETE',
  PROJECTION_RELEASE: 'PROJECTION_RELEASE_READY',
});

export const CURRENT_BLOCKED_STATE = Object.freeze({
  SOURCE_RIGHTS: 'BLOCKED_EXTERNAL_AUTHORITY',
  RECEIPT_AUTHORITY: 'CONTROL_IMPLEMENTATION_ADDED_PENDING_PROTECTED_MAIN_AND_EXTERNAL_TRUST_ROOT',
  CURRENT_SOLD_ADMISSION: 'CORE_COMPLETE_CONTROL_VALIDATED',
  CURRENT_SOLD_EVIDENCE: 'CORE_COMPLETE_CONTROL_VALIDATED',
  APPEND_ONLY_LEDGER: 'CODE_COMPLETE_NOT_ACTIVATED',
  CANDIDATE_EVIDENCE_PAIR: 'BLOCKED_NO_LAWFUL_LEDGER_ROWS',
  TRACK_B_ASSESSMENT: 'NOT_STARTED_EXACT_PAIR_ABSENT',
  PROJECTION_RELEASE: 'HOLD_NO_APPROVED_PROJECTION',
});

export const req = (value, code) => { if (!value) throw new Error(code); };
export const nonNegativeInt = value => Number.isInteger(value) && value >= 0;
export const sameStringSet = (a, b) => Array.isArray(a)
  && a.length === b.length
  && [...a].sort().every((value, index) => value === [...b].sort()[index]);
