import test from 'node:test';import assert from 'node:assert/strict';import {waitExactP2} from './wait-exact-p2-upstream-v1.mjs';
const sha='a'.repeat(40),repo='johnkim9524-collab/kaios_enterprise_repo';
const run=(id,status='completed',conclusion='success')=>({id,status,conclusion,path:'.github/workflows/kidults-asi-owned-source-intelligence-graph-v2.yml',head_sha:sha,head_branch:'main',repository:{full_name:repo},updated_at:new Date(100000).toISOString()});
function harness(index,{budgetMs=30000,main=sha}={}) {let clock=100000,round=0;const receipts=[],calls=[];return {receipts,calls,args:{sha,budgetMs,now:()=>clock,sleep:async ms=>{clock+=ms;round++},record:r=>receipts.push(r),read:async url=>{calls.push(url);if(url.endsWith('/branches/main'))return {name:'main',commit:{sha:main}};return typeof index==='function'?index(round,url):index}}};}
test('pending becomes exact-main success without dispatch or mutation',async()=>{const h=harness(n=>({total_count:1,workflow_runs:[run(1,n?'completed':'in_progress',n?'success':null)]}));assert.equal(await waitExactP2(h.args),'1');assert.equal(h.receipts[1].code,'EXACT_MAIN_P2_PENDING');assert(h.calls.every(x=>x.startsWith('/repos/')&& !x.includes('dispatch')));assert(h.calls.some(x=>x.includes(`head_sha=${sha}`)));});
test('missing exhausts bounded deadline with retained HOLD receipt',async()=>{const h=harness({total_count:0,workflow_runs:[]});await assert.rejects(waitExactP2(h.args),/WAIT_DEADLINE_EXHAUSTED/);assert.equal(h.receipts.at(-1).state,'HOLD');assert.equal(h.receipts[1].code,'EXACT_MAIN_P2_MISSING');});
test('terminal failure is distinct from missing',async()=>{const h=harness({total_count:1,workflow_runs:[run(1,'completed','failure')]});await assert.rejects(waitExactP2(h.args),/P2_TERMINAL_WITHOUT_SUCCESS/);});
test('old SHA response cannot select',async()=>{const h=harness({total_count:1,workflow_runs:[{...run(1),head_sha:'b'.repeat(40)}]});await assert.rejects(waitExactP2(h.args),/RUN_BINDING_INVALID/);});
test('main advance stops reads',async()=>{const h=harness({}, {main:'b'.repeat(40)});await assert.rejects(waitExactP2(h.args),/CURRENT_MAIN_CHANGED/);assert.equal(h.calls.length,1);});
test('pagination exhausts complete native index',async()=>{const rows=Array.from({length:101},(_,i)=>run(i+1,'completed','failure'));rows[100]=run(101);const h=harness((n,url)=>({total_count:101,workflow_runs:url.endsWith('page=1')?rows.slice(0,100):rows.slice(100)}));assert.equal(await waitExactP2(h.args),'101');});
test('truncated and drifting indexes fail closed',async()=>{for(const index of [{total_count:101,workflow_runs:[run(1)]},(n,url)=>({total_count:url.endsWith('page=1')?101:102,workflow_runs:Array.from({length:100},(_,i)=>run(i+1))})]){const h=harness(index);await assert.rejects(waitExactP2(h.args),/RUN_INDEX_(TRUNCATED|CHANGED_DURING_PAGINATION)/);}});
test('same SHA existing success remains contract-compatible while newer pending',async()=>{const h=harness({total_count:2,workflow_runs:[run(2,'in_progress',null),run(1)]});assert.equal(await waitExactP2(h.args),'1');});
test('transport error never leaks provider output or secrets',async()=>{const h=harness(()=>{throw new Error('secret TOKEN provider body')});await assert.rejects(waitExactP2(h.args),/^Error: NATIVE_READ_FAILED$/);assert(!JSON.stringify(h.receipts).includes('secret'));});
test('stale success and oversized index remain HOLD',async()=>{for(const index of [{total_count:1,workflow_runs:[{...run(1),updated_at:'1970-01-01T00:00:00Z'}]},{total_count:1001,workflow_runs:[]}]){const h=harness(index);if(index.total_count===1)h.args.now=()=>100000000;await assert.rejects(waitExactP2(h.args),/(SUCCESSFUL_P2_STALE|RUN_INDEX_LIMIT_EXCEEDED)/);}});
